# Generated by Django 5.2.5 on 2025-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='follow_up_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Nhận xét câu hỏi phụ'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='follow_up_question',
            field=models.TextField(blank=True, null=True, verbose_name='Câu hỏi phụ'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='follow_up_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm câu hỏi phụ'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='follow_up_transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung trả lời câu hỏi phụ'),
        ),
    ]
