# Generated by Django 5.2.4 on 2025-08-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_userprofile_class_name_userprofile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên môn học')),
                ('subject_code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn học')),
                ('quiz_data_file', models.CharField(blank=True, help_text='Ví dụ: data_analysis_quiz.json', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('question_id_in_barem', models.CharField(help_text='Ví dụ: Q1, Q2...', max_length=20, verbose_name='ID câu hỏi trong tệp barem')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qna.subject', verbose_name='Môn học')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(verbose_name='Nội dung trả lời')),
                ('score', models.FloatField(verbose_name='Điểm số')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Nhận xét của AI')),
                ('analysis', models.JSONField(null=True, verbose_name='Phân tích chi tiết')),
                ('exam_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question', verbose_name='Câu hỏi đã thi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.subject', verbose_name='Môn học')),
            ],
        ),
    ]
